# Generated by Django 4.1.7 on 2023-02-22 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tash', '0002_partiya'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='partiya',
            name='ifloslik',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='partiya',
            name='namlik',
            field=models.FloatField(blank=True),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rusum', models.CharField(max_length=20)),
                ('tr_num', models.CharField(max_length=20)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tash.firma')),
            ],
        ),
        migrations.CreateModel(
            name='Tashish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('nak_num', models.CharField(max_length=20)),
                ('sofVazn', models.FloatField()),
                ('ifloslik', models.FloatField()),
                ('namlik', models.FloatField()),
                ('xisobiy', models.FloatField()),
                ('kond', models.FloatField()),
                ('partiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tash.partiya')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tash.transport')),
            ],
        ),
    ]
