# Generated by Django 4.1.7 on 2023-02-23 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tash', '0003_firma_alter_partiya_ifloslik_alter_partiya_namlik_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firma',
            options={'verbose_name_plural': 'Ташувчи Фирмалар'},
        ),
        migrations.AlterModelOptions(
            name='partiya',
            options={'verbose_name_plural': 'Партиялар очиш'},
        ),
        migrations.AlterModelOptions(
            name='punkt',
            options={'verbose_name_plural': 'Пахта тозалаш масканлари'},
        ),
        migrations.AlterModelOptions(
            name='tashish',
            options={'verbose_name_plural': 'ПАХТАНИ ТАШИШ'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name_plural': 'Т/Р руйхатдан утказиш'},
        ),
        migrations.AlterField(
            model_name='firma',
            name='name',
            field=models.CharField(help_text='М: AGRMOMAX MCHJ', max_length=20, verbose_name='Фирма номи'),
        ),
        migrations.AlterField(
            model_name='partiya',
            name='bunt',
            field=models.CharField(max_length=20, verbose_name='Жой РАКАМИ'),
        ),
        migrations.AlterField(
            model_name='partiya',
            name='ifloslik',
            field=models.FloatField(blank=True, verbose_name='Ифлослиги'),
        ),
        migrations.AlterField(
            model_name='partiya',
            name='kond',
            field=models.FloatField(verbose_name='Кондицион вазни'),
        ),
        migrations.AlterField(
            model_name='partiya',
            name='namlik',
            field=models.FloatField(blank=True, verbose_name='Намлиги'),
        ),
        migrations.AlterField(
            model_name='partiya',
            name='nav',
            field=models.CharField(help_text='Анд-35,Анд-36,Шарк', max_length=30, verbose_name='Селекцион Нав'),
        ),
        migrations.AlterField(
            model_name='partiya',
            name='partiya',
            field=models.CharField(max_length=7, verbose_name='ПАРТИЯ РАКАМИ'),
        ),
        migrations.AlterField(
            model_name='partiya',
            name='snif',
            field=models.CharField(max_length=1, verbose_name='Пахтанинг снифи'),
        ),
        migrations.AlterField(
            model_name='partiya',
            name='sofVazn',
            field=models.FloatField(verbose_name='Соф вазни'),
        ),
        migrations.AlterField(
            model_name='partiya',
            name='sort',
            field=models.CharField(max_length=1, verbose_name='Пахтанинг Сорти'),
        ),
        migrations.AlterField(
            model_name='partiya',
            name='xisobiy',
            field=models.FloatField(verbose_name='Хисобий вазни'),
        ),
        migrations.AlterField(
            model_name='partiya',
            name='xosil',
            field=models.CharField(max_length=4, verbose_name='Йил'),
        ),
        migrations.AlterField(
            model_name='tashish',
            name='ifloslik',
            field=models.FloatField(verbose_name='Ифлослиги'),
        ),
        migrations.AlterField(
            model_name='tashish',
            name='kond',
            field=models.FloatField(blank=True, verbose_name='Кондицион Вазни'),
        ),
        migrations.AlterField(
            model_name='tashish',
            name='nak_num',
            field=models.CharField(max_length=20, verbose_name='Накладной раками'),
        ),
        migrations.AlterField(
            model_name='tashish',
            name='namlik',
            field=models.FloatField(verbose_name='Намлиги'),
        ),
        migrations.AlterField(
            model_name='tashish',
            name='partiya',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tash.partiya', verbose_name='Партия раками'),
        ),
        migrations.AlterField(
            model_name='tashish',
            name='sofVazn',
            field=models.FloatField(verbose_name='Соф Вазни'),
        ),
        migrations.AlterField(
            model_name='tashish',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tash.transport', verbose_name='Транспортни танланг'),
        ),
        migrations.AlterField(
            model_name='tashish',
            name='xisobiy',
            field=models.FloatField(blank=True, verbose_name='Хисобий Вазни'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='firma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tash.firma', verbose_name='Фирма'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='rusum',
            field=models.CharField(max_length=20, verbose_name='Транспорт маркаси'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='tr_num',
            field=models.CharField(max_length=20, verbose_name='Транспорт раками'),
        ),
    ]
