# Generated by Django 4.1.7 on 2023-02-23 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tash', '0004_alter_firma_options_alter_partiya_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partiya',
            name='xosil',
        ),
    ]
