# Generated by Django 4.1.7 on 2023-02-24 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tash', '0007_tashish_ptm'),
    ]

    operations = [
        migrations.AddField(
            model_name='partiya',
            name='ptm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tash.punkt'),
        ),
    ]
