# Generated by Django 4.1.7 on 2023-02-24 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tash', '0008_partiya_ptm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tashish',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tashish',
            name='ptm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ptm1', to='tash.punkt'),
        ),
    ]
