# Generated by Django 4.1.7 on 2023-02-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tash', '0010_alter_tashish_ptm'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaxtaNavi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_name', models.CharField(max_length=20)),
            ],
        ),
    ]
