# Generated by Django 4.1.7 on 2023-02-25 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tash', '0016_remove_partiya_seleksiya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partiya',
            name='nav',
            field=models.ForeignKey(help_text='Анд-35,Анд-36,Шарк', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tash.paxtanavi', verbose_name='Селекцион Нав'),
        ),
    ]
