# Generated by Django 4.1.7 on 2023-02-25 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tash', '0017_alter_partiya_nav'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paxtanavi',
            options={'verbose_name_plural': 'Пахта Навлари'},
        ),
    ]
