# Generated by Django 4.1.7 on 2023-02-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tash', '0019_alter_partiya_snif_alter_partiya_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.BooleanField(default=False)),
            ],
        ),
    ]
