# Generated by Django 4.1.7 on 2023-02-25 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tash', '0021_displaysetting_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='displaysetting',
            options={'verbose_name_plural': 'DISPLAY СОЗЛАМАЛАРИ'},
        ),
        migrations.AddField(
            model_name='transport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='displaysetting',
            name='display',
            field=models.BooleanField(default=False, verbose_name='Дисплейни учириш'),
        ),
    ]
