# Generated by Django 4.1.7 on 2023-02-25 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tash', '0022_alter_displaysetting_options_transport_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='narx',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='firma',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
